language: scala
scala:
- 2.12.8
jdk:
- oraclejdk8
script:
- make build
- |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    echo "dump change list"
    FILES=`git diff $(git log --first-parent master --oneline |cut -f1 -d' '|head -n2|tac|awk '{if(NR%2)ORS="...";else ORS="";print}') --name-only`
    echo $FILES
    echo $FILES| grep -E '^src|azure|build\.sbt'&& make deploy/azure AZURE_DEPLOY_USER=$AZURE_DEPLOY_USER AZURE_DEPLOY_PASSWORD=$AZURE_DEPLOY_PASSWORD AZURE_DEPLOY_SITE=$AZURE_DEPLOY_SITE || echo 'no deploy for Azure'
  fi

